language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

install: composer install --dev

before_script:
  - cp config/db-config.sample.php config/db-config.php
  - mysql -e 'CREATE DATABASE labs;'

script:
  - cat vendor/clearbooks/labs-schema/sql/*.sql | mysql -uroot labs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
